// <auto-generated />
namespace ShopNuocHoaTMD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateOrder_removeDeliveredDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateOrder_removeDeliveredDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202211150902409_updateOrder_removeDeliveredDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
